### ISSUE TITLE
Add outfitter integration

### ISSUE THREAD

**Issue by Bonkeybee** [kurapica/BagView#2]
The ability to filter by equipment sets from the outfitter addon would be great, likely by using the outfitter global vars/functions to create a dynamic rule that is updated when a change to outfitter is made.

![image](https://user-images.githubusercontent.com/9619823/142781714-cec50cd9-2778-49e7-9689-2b70113f92c2.png)

**Comment by kurapica** [comment]
There is already a rule [IsEquipSet] in it, and you can use the equip set's name in the filter if you need seperate them
