### ISSUE TITLE
Except the Any, Backpack, Container 1 2 3 4 rules, no rule works on my side.

### ISSUE THREAD

**Issue by oriofdarkforest** [kurapica/BagView#3]
I am unsure if it is a setting error on my part, but none of the rules seem to be functioning correctly except for the default view and rule Any. For instance, I added Container 1, created a rule, clicked "Add Rule," selected the equipment configuration plan, and clicked "Apply." However, when I clicked on the newly created view in my backpack, nothing was displayed.

I'm playing 10.1.

got the error message
```
1x BagView/Template.lua:371: [string "            local containerList, itemList, ..."]:32: attempt to call global 'GetContainerItemEquipmentSetInfo' (a nil value)
[string "@Scorpio/Modules/Core.lua"]:345: in function <Scorpio/Modules/Core.lua:198>
[string "@Scorpio/Modules/Core.lua"]:432: in function <Scorpio/Modules/Core.lua:198>
[string "=(tail call)"]: ?

Locals:
now = 418701.380000
r_Header = <table> {
 1 = <no value>
 2 = <no value>
 3 = <no value>
 4 = <no value>
 5 = <no value>
 -1 = 6
}
runoutIdx = nil
(for index) = 5
(for limit) = 5
(for step) = 1
i = 5
task = <no value>
ok = false
msg = "BagView/Template.lua:371: [string "            local containerList, itemList, ..."]:32: attempt to call global 'GetContainerItemEquipmentSetInfo' (a nil value)"
queueTaskList = <function> defined @Scorpio/Modules/Core.lua:187
_CancelSingleAsync = <table> {
}
_RunSingleAsync = <table> {
}
_SingleAsync = <table> {
}
_ResidentService = <table> {
  = <function> defined @Scorpio/Modules/Core.lua:621
  = <function> defined @Scorpio/Modules/Core.lua:621
  = <function> defined @Scorpio/Modules/Core.lua:621
  = <function> defined @Scorpio/Modules/Core.lua:621
  = <function> defined @Scorpio/Modules/Core.lua:621
  = <function> defined @Scorpio/Modules/Core.lua:621
  = <function> defined @Scorpio/Modules/Core.lua:621
  = <function> defined @Scorpio/Modules/Core.lua:621
  = <function> defined @Scorpio/Modules/Core.lua:621
  = <function> defined @Scorpio/Modules/Core.lua:621
  = <function> defined @Scorpio/Modules/Core.lua:621
}
recycleCache = <function> defined @Scorpio/Modules/Core.lua:100
processPhase = <function> defined @Scorpio/Modules/Core.lua:198
```

**Comment by kurapica** [comment]
It seems blz have move the `GetContainerItemEquipmentSetInfo` api from global to `C_Container`, if can be fixed by add 

```lua
local GetContainerItemEquipmentSetInfo = _G.GetContainerItemEquipmentSetInfo or _G.C_Container and _G.C_Container.GetContainerItemEquipmentSetInfo
```

After line 286 in the BagView/Template.lua. Or just wait me release a new version tonight

**Comment by oriofdarkforest** [comment]
I added that line and the error message disappeared.
But my view still not showing anything.

![image](https://github.com/kurapica/BagView/assets/72719841/65f248ec-9829-44ba-9770-510d60e09584)

Could you please help me check am I setting anything wrong? Love this addon but can't use it T.T

**Comment by kurapica** [comment]
No, if you can create rule in the rule desinger, it's allowed. Blz may modify some api returns, I need check it tonight

**Comment by kurapica** [comment]
Blz has change one api's result to table, cost more memory and will reduce the performance, don't know why, maybe just for KPI.

Add a fix in r024, but as I check, the in equip set feature is still broken, since blz leave that bug open since 2022. Maybe you can use tooltip filter if you need that, other settings should works now.
